### ISSUE TITLE
text align center not apply when fixed width

### ISSUE THREAD

**Issue by starofsky** [FokkeZB/nl.fokkezb.button#24] opened 2015-03-19 09:19 UTC
i can't set align title center when fixed width.

\<Widget class="button_h1" src="nl.fokkezb.button" onClick="function" title="Title button" style="bs-default" id="button1" /\>

".button_h1": {
    width: 220,
    height: 40,
    textAlign: Titanium.UI.TEXT_ALIGNMENT_CENTER
}

**Comment by starofsky** [comment] 2015-03-20 02:20
In your example version 1.4. I changed 
".icon": {
	iconFont: 'FontAwesome',
	icon: Alloy.Globals.fa.powerOff,
        textAlign: "center",
	width: "20%"
}
and buttons aren't also center

**Comment by FokkeZB** [comment] 2015-03-25 08:53
I just added a test case for this issue in the updates [test](https://github.com/FokkeZB/nl.fokkezb.button/tree/test) app (see last tab in app) and I can't reproduce. The text correctly centers. Please provide a PR for the test branch with a failing test case.

**Comment by starofsky** [comment] 2015-03-27 02:37
The problem is happen when we use style (ios, default...etc..), when code build inner layout we have padding left and right so the label cannot center, i applied a temp fix by check if have fix width, i will remove padding, that good for me now.
The last tab in test app padding don't have left and right, so thay work right.

**Comment by FokkeZB** [comment] 2015-03-27 06:33
Please do a PR where the test case matches your bug so that I can fix it.

**Comment by FokkeZB** [comment] 2015-03-30 07:23
I've merged your PR #27, thanks for that.

It did reproduce the "bug", however... I saw that you've modified the button the custom-tab and this button does not set `textAlign` to center. I moved the changes to a button on the test-tab, added `textAlign` and as you can see it works fine:

https://github.com/FokkeZB/nl.fokkezb.button/blob/test/app/styles/index.tss#L75

![ios simulator screen shot 30 mar 2015 09 18 19](https://cloud.githubusercontent.com/assets/2699409/6891785/5a1d2466-d6be-11e4-9445-f5a2755a0eae.png)

**Closed by FokkeZB** 2015-03-30 07:23 UTC
Labels: invalid
